# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'goalsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for goalsApp

  pod 'Firebase/Analytics'
  target 'goalsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'goalsAppUITests' do
    # Pods for testing
  end

end
